#!/usr/bin/env python3
"""
Targeted purge of HTML_CACHE KV entries poisoned by the soft-404 bug.

BACKGROUND
----------
When the Cloudflare Pages project had `not_found_handling` set to the
single-page-application fallback, `env.ASSETS.fetch()` returned the
homepage (200) for every missing path. The Advanced Mode Worker happily
cached that response under the bogus URL's key, so Bing & co. saw
hundreds of URLs like `html:/nutanix-ce` that returned the homepage with
a HIT. Reloading the site template isn't enough — those poisoned KV
entries hang around until their absolute TTL (up to 1h) expires.

This script lists every `html:*` key in HTML_CACHE and deletes the ones
whose path is NOT in public/path-manifest.json (the authoritative list
of legitimate content URLs, generated by scripts/generate_soft404_artefacts.py).

Use this INSTEAD OF scripts/purge_html_kv_cache.py when you only want to
evict the ghost entries and preserve the warm cache for real pages.

Usage:
    python3 scripts/purge_soft404_kv_cache.py [--dry-run] [--manifest PATH]

Required environment variables:
    CLOUDFLARE_API_TOKEN   — API token with KV:Edit
    CLOUDFLARE_ACCOUNT_ID  — Cloudflare account ID
Optional:
    KV_NAMESPACE_ID        — Override the HTML_CACHE namespace ID
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

DEFAULT_NAMESPACE_ID = "5528672ccf0644c9bd65e7de8b629189"
CF_API_BASE = "https://api.cloudflare.com/client/v4"
BULK_DELETE_LIMIT = 10_000
REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = REPO_ROOT / "public" / "path-manifest.json"


def cf_request(method: str, path: str, token: str, account_id: str, body=None):
    url = f"{CF_API_BASE}/accounts/{account_id}{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(
        url,
        data=data,
        method=method,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json",
        },
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body_text = e.read().decode(errors="replace")
        print(f"❌ HTTP {e.code} from Cloudflare API: {body_text}", file=sys.stderr)
        sys.exit(1)


def list_all_keys(token: str, account_id: str, namespace_id: str) -> list[str]:
    keys: list[str] = []
    cursor = None
    page = 1
    while True:
        path = (
            f"/storage/kv/namespaces/{namespace_id}/keys?limit=1000&prefix=html:"
        )
        if cursor:
            path += f"&cursor={cursor}"
        print(f"  📋 Page {page}…", end=" ", flush=True)
        result = cf_request("GET", path, token, account_id)
        if not result.get("success"):
            print(f"\n❌ API error: {result.get('errors')}", file=sys.stderr)
            sys.exit(1)
        batch = result.get("result", [])
        keys.extend(k["name"] for k in batch)
        print(f"{len(batch)} keys")
        cursor = result.get("result_info", {}).get("cursor")
        if not cursor or not batch:
            break
        page += 1
    return keys


def load_manifest(manifest_path: Path) -> set[str]:
    if not manifest_path.exists():
        print(
            f"❌ manifest {manifest_path} not found — run "
            "scripts/generate_soft404_artefacts.py first",
            file=sys.stderr,
        )
        sys.exit(1)
    paths = json.loads(manifest_path.read_text(encoding="utf-8"))
    normalised: set[str] = set()
    for p in paths:
        normalised.add(p)
        # Accept both trailing-slash and bare forms (mirrors the Worker).
        if p == "/":
            normalised.add("/index.html")
        elif p.endswith("/"):
            normalised.add(p[:-1])
        else:
            normalised.add(p + "/")
    return normalised


def classify(keys: list[str], valid_paths: set[str]) -> tuple[list[str], list[str]]:
    """Split keys into (poisoned, legitimate)."""
    poisoned: list[str] = []
    legitimate: list[str] = []
    for key in keys:
        # Keys are stored as `html:<path>`. Anything without the prefix
        # is left alone.
        if not key.startswith("html:"):
            legitimate.append(key)
            continue
        path = key[len("html:"):]
        if path in valid_paths:
            legitimate.append(key)
        else:
            poisoned.append(key)
    return poisoned, legitimate


def bulk_delete(token: str, account_id: str, namespace_id: str,
                keys: list[str], dry_run: bool) -> None:
    if not keys:
        print("ℹ️  Nothing to delete.")
        return
    if dry_run:
        print(f"🔍 DRY RUN — would delete {len(keys)} poisoned keys:")
        for k in keys[:30]:
            print(f"   {k}")
        if len(keys) > 30:
            print(f"   … and {len(keys) - 30} more")
        return
    deleted = 0
    for i in range(0, len(keys), BULK_DELETE_LIMIT):
        batch = keys[i:i + BULK_DELETE_LIMIT]
        path = f"/storage/kv/namespaces/{namespace_id}/bulk/delete"
        result = cf_request("POST", path, token, account_id, body=batch)
        if result.get("success"):
            deleted += len(batch)
            print(f"  🗑️  {deleted}/{len(keys)} deleted")
        else:
            print(f"❌ Bulk delete failed: {result.get('errors')}", file=sys.stderr)
            sys.exit(1)
    print(f"\n✅ Purged {deleted} poisoned KV entries")


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--manifest", default=str(DEFAULT_MANIFEST),
        help=f"Path to path-manifest.json (default: {DEFAULT_MANIFEST})",
    )
    parser.add_argument(
        "--namespace-id", default=None,
        help="Override KV namespace ID (default: HTML_CACHE from wrangler.toml)",
    )
    args = parser.parse_args()

    token = os.environ.get("CLOUDFLARE_API_TOKEN")
    account_id = os.environ.get("CLOUDFLARE_ACCOUNT_ID")
    namespace_id = (
        args.namespace_id
        or os.environ.get("KV_NAMESPACE_ID")
        or DEFAULT_NAMESPACE_ID
    )
    if not token or not account_id:
        print(
            "❌ Set CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID before running.",
            file=sys.stderr,
        )
        return 1

    valid = load_manifest(Path(args.manifest))
    print(f"📚 Loaded {len(valid)} legitimate path variants from manifest")

    keys = list_all_keys(token, account_id, namespace_id)
    print(f"📦 Namespace {namespace_id} holds {len(keys)} html:* keys")

    poisoned, legitimate = classify(keys, valid)
    print(f"✅ {len(legitimate)} keys map to legitimate paths (kept)")
    print(f"💀 {len(poisoned)} keys are poisoned soft-404 entries (purging)")

    bulk_delete(token, account_id, namespace_id, poisoned, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
